name: Enviar mensagem para o Telegram

on:
  schedule:
    - cron: '15 23 * * *'
      timezone: 'America/Sao_Paulo'  # Usando o timezone correto
  workflow_dispatch:  # Permite rodar manualmente também

jobs:
  send-telegram:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Instalar dependências
        run: pip install requests

      - name: Rodar o script
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python3 ./send_message.py  # Caminho para o script na raiz
