name: Enviar mensagem para o Telegram

on:
  schedule:
    - cron: '0 13 * * *' # Horário UTC! Exemplo: 13:00 UTC todo dia (10:00 no Brasil com -3h)
  workflow_dispatch: # Permite rodar manualmente também

jobs:
  send-telegram:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Instalar dependências
        run: pip install requests

      - name: Rodar o script
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python send_message.py
        
