name: Enviar mensagem para o Telegram

on:
  schedule:
    - cron: '*/2 * * * *'  # Executa a cada 2 minutos
      timezone: 'America/Sao_Paulo'  # Define o fuso horário

jobs:
  send-telegram:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Rodar o script
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python3 ./send_message.py  # Executa o script Python
