name: Enviar mensagem para o Telegram

on:
 on:
  schedule:
    - cron: '*/5 * * * *'
      timezone: 'America/Sao_Paulo'
  workflow_dispatch: # Permite rodar manualmente também

jobs:
  send-telegram:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Instalar dependências
        run: pip install requests

      - name: Exibir horário atual (debug)
        run: |
          echo "Horário UTC atual:"
          date -u
          echo "Horário local de São Paulo (Minas Gerais):"
          TZ=America/Sao_Paulo date

      - name: Rodar o script
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python send_message.py
